[package]
name = "ch10-render-hex-threadpool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7"
crossbeam-utils = "0.7"
rayon = "1"
svg = "0.6"
